### ISSUE TITLE
Reload models

### ISSUE THREAD

**Issue by Arnold1** [serizba/cppflow#19] opened 2020-02-13 05:16 UTC
Hi,

what is the suggested model on the fly? lets say I calling model.run (to do the prediction) in production and want to reload a new model every 6 hours and have 50 models.

what tensorflow version do you currently support? 1.x and 2.1.x? does it support both if not why not?

edit: in the Tensorflow page I read: ```Note: There is no libtensorflow support for TensorFlow 2 yet. It is expected in a future release.``` any idea why its not out yet? what is improved with tensorflow 2?

the latest you can download seems to be: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz

also can you say anything about required ram memory to load 1 model? I assume the model will be loaded from disk to memory - after the first model.run call?
```
    // Read the graph
    Model model("graph.pb");
    model.init();
```

Thanks

**Comment by serizba** [comment] 2020-02-15 08:19
CppFlow only acts as an interface to ease the use of the TensorFlow C API. For this reason, the version support depends directly on the official C API, which currently does not support TensorFlow 2.0. From TensorFlow C API [webpage](https://www.tensorflow.org/install/lang_c):

> Note: There is no libtensorflow support for TensorFlow 2 yet. It is expected in a future release.

Also, the performance requirements and memory consumption depends entirely on the implementation of the C API, and therefore it is not controlled by this project.

**Comment by Arnold1** [comment] 2020-02-17 07:04
@serizba thanks for reply. what happens if I need to reload the model during runtime lets say every hour?

**Comment by Arnold1** [comment] 2020-05-29 02:56
hi did you see my msg?

**Comment by serizba** [comment] 2020-05-29 08:24
Hi,
What do you exactly mean by reloading the model? 

- Do you want to use a new checkpoint? If that is the case I would recommend calling `model.restore('path/to/ckpt) ` again. 

- Do you want to load a new .pb file? In that case I would say remove and delete the old model variable, check that no memory leaks are left, and create a new model.

Anyways, as I said CppFlow only acts as an interface of the TensorFlow C API. All the requirements, and the best behaviour to take depends on the C API, and therefore you should read its documentation or ask them. My personal project is independent from the C API.

**Comment by serizba** [comment] 2020-06-12 08:36
Hi,

I would say that the issue is more related to the C API internal details than with this repository. 

Also, as looks like there is no more activity I proceed to close the issue.

**Closed by serizba** 2020-06-12 08:36 UTC
